/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TranscriptContract {
  window: TranscriptWindow;
  changes: TranscriptChanges;
  [k: string]: unknown;
}
export interface TranscriptWindow {
  session_id: string;
  generation: string;
  generated_at: string;
  entries: TranscriptEntry[];
  before_cursor: string | null;
  after_window_cursor: string | null;
  has_older: boolean;
  has_newer: boolean;
  change_cursor: string;
  coverage: Coverage;
  [k: string]: unknown;
}
export interface TranscriptEntry {
  entry_id: string;
  session_id: string;
  task_id: string | null;
  thread_id: string | null;
  turn_id: string | null;
  first_seq: string;
  revision_seq: string;
  kind: string;
  title: string;
  phase: string | null;
  state: string;
  raw_state: string | null;
  observed_at: string;
  source_timestamp: string | null;
  started_at: string | null;
  ended_at: string | null;
  source: Source;
  source_item_id: string | null;
  related_entry_ids: string[];
  blocks: TranscriptBlock[];
  raw_event_count: number;
  coverage: Coverage;
  tool_name: string | null;
  command: string | null;
  cwd: string | null;
  exit_code: number | null;
  duration_ms: number | null;
  decision: string | null;
  [k: string]: unknown;
}
export interface Source {
  backend: string;
  version: string | null;
  origin: string;
  [k: string]: unknown;
}
export interface TranscriptBlock {
  block_id: string;
  kind: string;
  mime_type: string;
  preview: string;
  preview_truncated: boolean;
  content_ref: string;
  recorded_bytes: number;
  [k: string]: unknown;
}
export interface Coverage {
  source_truncated: boolean;
  capture_gap: boolean;
  redacted: boolean;
  missing_parts: string[];
  [k: string]: unknown;
}
export interface TranscriptChanges {
  session_id: string;
  generation: string;
  generated_at: string;
  changes: EntryChange[];
  next_cursor: string;
  has_more: boolean;
  [k: string]: unknown;
}
export interface EntryChange {
  seq: string;
  upserts: TranscriptEntry[];
  [k: string]: unknown;
}
