/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TranscriptContract {
  sessions: SessionPage;
  session: SessionDetail;
  tasks: TaskPage;
  task: TaskDetail;
  window: TranscriptWindow;
  changes: TranscriptChanges;
  task_tree: SessionTaskTree;
  search: SearchResults;
  content: ContentPage;
  memory: MemoryPage;
  memory_source: MemorySource;
  memory_injections: MemoryInjectionPage;
  [k: string]: unknown;
}
export interface SessionPage {
  items: Session[];
  total: number;
  offset: number;
  has_more: boolean;
  [k: string]: unknown;
}
export interface Session {
  kind: string;
  execution: ExecutionTarget | null;
  session_id: string;
  context_key: string;
  title: string;
  thread_id: string | null;
  state: string;
  backend: string;
  created_at: string;
  updated_at: string;
  task_count: number;
  spawned_by_task_id: string | null;
  execution_uncertain: boolean;
  coverage: Coverage;
  origin: string;
  previous_session_id: string | null;
  [k: string]: unknown;
}
/**
 * Resolved execution intent, frozen when a task is admitted.
 */
export interface ExecutionTarget {
  backend: string;
  driver: 'codex' | 'claude-code';
  model?: string | null;
  reasoning?: string | null;
  turn_timeout_seconds: number;
  sources?: {
    [k: string]: string;
  };
}
export interface Coverage {
  source_truncated: boolean;
  redacted: boolean;
  [k: string]: unknown;
}
export interface SessionDetail {
  kind: string;
  execution: ExecutionTarget | null;
  session_id: string;
  context_key: string;
  title: string;
  thread_id: string | null;
  state: string;
  backend: string;
  created_at: string;
  updated_at: string;
  task_count: number;
  spawned_by_task_id: string | null;
  execution_uncertain: boolean;
  coverage: Coverage;
  origin: string;
  previous_session_id: string | null;
  tasks: Turn[];
  has_more_tasks: boolean;
  runtime: SessionMetadata | null;
  history_error?: string | null;
  [k: string]: unknown;
}
export interface Turn {
  kind: string;
  execution: ExecutionTarget | null;
  task_id: string;
  turn_id: string | null;
  title: string;
  state: string;
  cwd: string | null;
  revision: string | null;
  created_at: string;
  ended_at: string | null;
  [k: string]: unknown;
}
export interface SessionMetadata {
  id: string;
  backend: string;
  cwd: string | null;
  model: string | null;
  provider: string | null;
  reasoning_effort: string | null;
  cli_version: string | null;
  created_at: string | null;
  updated_at: string | null;
  [k: string]: unknown;
}
export interface TaskPage {
  items: Task[];
  total: number;
  has_more: boolean;
  [k: string]: unknown;
}
export interface Task {
  kind: string;
  execution: ExecutionTarget | null;
  task_id: string;
  context_key: string;
  status: string;
  action: string;
  backend: string;
  session_id: string | null;
  coalesced_into: string | null;
  spawned_by_task_id: string | null;
  context_generation: number;
  error: string | null;
  created_at: number;
  updated_at: number;
  title: string;
  plugin_id: string;
  [k: string]: unknown;
}
export interface TaskDetail {
  kind: string;
  execution: ExecutionTarget | null;
  task_id: string;
  context_key: string;
  status: string;
  action: string;
  backend: string;
  session_id: string | null;
  coalesced_into: string | null;
  spawned_by_task_id: string | null;
  context_generation: number;
  error: string | null;
  created_at: number;
  updated_at: number;
  dedupe_key: string | null;
  entry_id: string | null;
  turn_id: string | null;
  thread_id: string | null;
  event_worktree: string | null;
  task: {
    [k: string]: unknown;
  };
  session_thread_id: string | null;
  session_backend: string;
  lease_expires_at: number | null;
  lifecycle: string;
  waiting_for: string[];
  children: TaskChild[];
  subtask_result: TaskEvidence | null;
  history_error?: string | null;
  [k: string]: unknown;
}
export interface TaskChild {
  kind: string;
  execution: ExecutionTarget | null;
  task_id: string;
  status: string;
  context_key: string;
  backend: string;
  [k: string]: unknown;
}
export interface TaskEvidence {
  summary: string;
  artifacts: TaskResultArtifact[];
  data: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface TaskResultArtifact {
  name: string;
  sha256: string;
  bytes: number;
  path: string;
  [k: string]: unknown;
}
export interface TranscriptWindow {
  session_id: string;
  generation: string;
  generated_at: string;
  entries: TranscriptEntry[];
  before_cursor: string | null;
  after_window_cursor: string | null;
  has_older: boolean;
  has_newer: boolean;
  change_cursor: string;
  coverage: Coverage;
  [k: string]: unknown;
}
export interface TranscriptEntry {
  entry_id: string;
  session_id: string;
  task_id: string | null;
  thread_id: string | null;
  turn_id: string | null;
  first_seq: string;
  revision_seq: string;
  kind: string;
  title: string;
  phase: string | null;
  state: string;
  raw_state: string | null;
  observed_at: string;
  started_at: string | null;
  completed_at: string | null;
  recorded_at: string | null;
  source: Source;
  source_item_id: string | null;
  blocks: TranscriptBlock[];
  coverage: Coverage;
  tool_name: string | null;
  command: string | null;
  cwd: string | null;
  exit_code: number | null;
  duration_ms: number | null;
  decision: string | null;
  [k: string]: unknown;
}
export interface Source {
  backend: string;
  version: string | null;
  origin: string;
  [k: string]: unknown;
}
export interface TranscriptBlock {
  block_id: string;
  kind: string;
  mime_type: string;
  preview: string;
  preview_truncated: boolean;
  content_ref: string;
  recorded_bytes: number;
  [k: string]: unknown;
}
export interface TranscriptChanges {
  session_id: string;
  generation: string;
  generated_at: string;
  changes: EntryChange[];
  next_cursor: string;
  has_more: boolean;
  [k: string]: unknown;
}
export interface EntryChange {
  seq: string;
  upserts: TranscriptEntry[];
  [k: string]: unknown;
}
export interface SessionTaskTree {
  parent: TaskLink | null;
  groups: TaskTreeNode[];
  has_more: boolean;
  [k: string]: unknown;
}
export interface TaskLink {
  task_id: string;
  session_id: string | null;
  title: string;
  [k: string]: unknown;
}
export interface TaskTreeNode {
  kind: string;
  execution: ExecutionTarget | null;
  task_id: string;
  session_id: string | null;
  title: string;
  backend: string;
  purpose: string | null;
  status: string;
  created_at: string;
  waiting: boolean;
  summary: string | null;
  error: string | null;
  artifacts: TaskArtifact[];
  children: TaskTreeNode[];
  [k: string]: unknown;
}
export interface TaskArtifact {
  name: string;
  sha256: string;
  bytes: number;
  [k: string]: unknown;
}
export interface SearchResults {
  items: SearchHit[];
  has_more: boolean;
  [k: string]: unknown;
}
export interface SearchHit {
  entry_id: string;
  task_id: string | null;
  title: string;
  snippet: string;
  block_id: string;
  content_ref: string;
  offset: number;
  [k: string]: unknown;
}
export interface ContentPage {
  text: string;
  content_ref: string;
  offset: number;
  next_offset: number | null;
  recorded_bytes: number;
  [k: string]: unknown;
}
export interface MemoryPage {
  enabled: boolean;
  count: number;
  domains: MemoryDomain[];
  topics: MemoryTopic[];
  items: MemorySourceSummary[];
  summary_count: number;
  summaries: MemorySummary[];
  has_more: boolean;
  [k: string]: unknown;
}
export interface MemoryDomain {
  id: string;
  count: number;
  [k: string]: unknown;
}
export interface MemoryTopic {
  name: string;
  count: number;
  [k: string]: unknown;
}
export interface MemorySourceSummary {
  id: string;
  domain: string;
  task_id: string;
  context_key: string;
  context_generation: number;
  source_order: number;
  title: string;
  topics: string[];
  sources: string[];
  revision: string;
  updated_at: string;
  complete: boolean;
  [k: string]: unknown;
}
export interface MemorySummary {
  id: string;
  domain: string;
  context_key: string;
  context_generation: number;
  body: string;
  sources: string[];
  source_revisions: {
    [k: string]: string;
  };
  revision: string;
  updated_at: string;
  stale?: boolean;
  [k: string]: unknown;
}
export interface MemorySource {
  id: string;
  domain: string;
  task_id: string;
  context_key: string;
  context_generation: number;
  source_order: number;
  title: string;
  body: string;
  topics: string[];
  sources: string[];
  revision: string;
  updated_at: string;
  complete: boolean;
  [k: string]: unknown;
}
export interface MemoryInjectionPage {
  items: MemoryInjection[];
  has_more: boolean;
  [k: string]: unknown;
}
export interface MemoryInjection {
  backend: string;
  thread_id: string;
  turn_id: string;
  started_at: string;
  prompt: string;
  bytes: number;
  selected: MemoryInjectionSelection[];
  skipped: MemoryInjectionSelection[];
  [k: string]: unknown;
}
export interface MemoryInjectionSelection {
  id: string;
  revision: string;
  reason: string;
  [k: string]: unknown;
}
